version: '3.8'
services:
  localstack:
    image: 'localstack/localstack:latest'
    container_name: localstack_main
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
      - AWS_REGION=us-east-1
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
